export const state = () => ({
  today,
})

export const mutations = {
  addTask(state, newTask) {
    state.tasks.today.push(newTask)
  },
}

export const actions = {
  addTask({ commit }) {
    commit('addTask', commit)
  },
}

const today = [
  {
    id: '8F2B4F16',
    done: 'TRUE',
    repeat: '1 8 6 9 2',
    estimate: 25,
    result: 21,
    section: 1,
    name: 'mollis molestie',
    project: 'Work',
    start: '6:03',
    end: '6:24',
    date: '2020-04-30',
  },
  {
    id: 'F652540A',
    done: 'TRUE',
    repeat: '',
    estimate: 26,
    result: 37,
    section: 1,
    name: 'ante ipsum',
    project: 'Rest',
    start: '6:24',
    end: '7:01',
    date: '2020-04-30',
  },
  {
    id: 'DDFE5DCA',
    done: 'TRUE',
    repeat: '',
    estimate: 22,
    result: 19,
    section: 1,
    name: 'integer tincidunt',
    project: 'Create App',
    start: '7:01',
    end: '7:20',
    date: '2020-04-30',
  },
  {
    id: '8E60E509',
    done: 'TRUE',
    repeat: '',
    estimate: 7,
    result: 14,
    section: 1,
    name: 'porta volutpat',
    project: 'Create App',
    start: '7:20',
    end: '7:34',
    date: '2020-04-30',
  },
  {
    id: '910C105D',
    done: 'TRUE',
    repeat: '9 8 0 4 1',
    estimate: 8,
    result: 12,
    section: 1,
    name: 'ultrices phasellus',
    project: 'Transport',
    start: '7:34',
    end: '7:46',
    date: '2020-04-30',
  },
  {
    id: 'FC0C6C81',
    done: 'TRUE',
    repeat: '',
    estimate: 20,
    result: 21,
    section: 1,
    name: 'nunc viverra',
    project: 'Grooming',
    start: '7:46',
    end: '8:07',
    date: '2020-04-30',
  },
  {
    id: '2B813602',
    done: 'TRUE',
    repeat: '3 9 2 5 7',
    estimate: 12,
    result: 19,
    section: 1,
    name: 'ante ipsum',
    project: 'Grooming',
    start: '8:07',
    end: '8:26',
    date: '2020-04-30',
  },
  {
    id: 'C0377239',
    done: 'TRUE',
    repeat: '6 3 7 8 3',
    estimate: 16,
    result: 28,
    section: 2,
    name: 'sapien arcu',
    project: 'Household',
    start: '8:26',
    end: '8:54',
    date: '2020-04-30',
  },
  {
    id: '58D3A6F0',
    done: 'TRUE',
    repeat: '1 7 4 5 0',
    estimate: 28,
    result: 41,
    section: 2,
    name: 'mi pede',
    project: 'Rest',
    start: '8:54',
    end: '9:35',
    date: '2020-04-30',
  },
  {
    id: '1925FBD2',
    done: 'TRUE',
    repeat: '2 8 2 4 1',
    estimate: 18,
    result: 25,
    section: 2,
    name: 'ornare consequat',
    project: 'Rest',
    start: '9:35',
    end: '10:00',
    date: '2020-04-30',
  },
  {
    id: '5F456254',
    done: 'TRUE',
    repeat: '3 2 0 5 9',
    estimate: 6,
    result: 9,
    section: 2,
    name: 'curabitur in',
    project: 'Rest',
    start: '10:00',
    end: '10:09',
    date: '2020-04-30',
  },
  {
    id: 'D3033E5C',
    done: 'TRUE',
    repeat: '9 1 9 4 5',
    estimate: 13,
    result: 19,
    section: 2,
    name: 'ac consequat',
    project: 'Work',
    start: '10:09',
    end: '10:28',
    date: '2020-04-30',
  },
  {
    id: 'F51368F6',
    done: 'TRUE',
    repeat: '2 4 4 9 0',
    estimate: 7,
    result: 21,
    section: 2,
    name: 'nibh quisque',
    project: 'Create App',
    start: '10:28',
    end: '10:49',
    date: '2020-04-30',
  },
  {
    id: '5E085E52',
    done: 'TRUE',
    repeat: '7 9 4 6 4',
    estimate: 29,
    result: 32,
    section: 3,
    name: 'mauris eget',
    project: 'Grooming',
    start: '10:49',
    end: '11:21',
    date: '2020-04-30',
  },
  {
    id: 'C76B8F70',
    done: 'TRUE',
    repeat: '1 0 4 7 5',
    estimate: 10,
    result: 23,
    section: 3,
    name: 'nunc purus',
    project: 'Sleep',
    start: '11:21',
    end: '11:44',
    date: '2020-04-30',
  },
  {
    id: '2D1B2926',
    done: 'TRUE',
    repeat: '9 1 7 5 3',
    estimate: 21,
    result: 26,
    section: 4,
    name: 'sapien in',
    project: 'Transport',
    start: '11:44',
    end: '12:10',
    date: '2020-04-30',
  },
  {
    id: 'C234D3AF',
    done: 'FALSE',
    repeat: '',
    estimate: 21,
    result: '',
    section: 4,
    name: 'lacus morbi',
    project: 'Eating',
    start: '12:10',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '7BC5E536',
    done: 'FALSE',
    repeat: '6 6 3 1 0',
    estimate: 18,
    result: '',
    section: 4,
    name: 'donec ut',
    project: 'Create App',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '0E69F54C',
    done: 'FALSE',
    repeat: '5 2 0 8 8',
    estimate: 9,
    result: '',
    section: 4,
    name: 'dui luctus',
    project: 'Work',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '44D7A446',
    done: 'FALSE',
    repeat: '',
    estimate: 12,
    result: '',
    section: 4,
    name: 'vel pede',
    project: 'Grooming',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: 'F27E571B',
    done: 'FALSE',
    repeat: '',
    estimate: 14,
    result: '',
    section: 4,
    name: 'volutpat quam',
    project: 'Hobby',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '6E0EB566',
    done: 'FALSE',
    repeat: '',
    estimate: 23,
    result: '',
    section: 4,
    name: 'morbi ut',
    project: 'Hobby',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: 'B1416B5C',
    done: 'FALSE',
    repeat: '',
    estimate: 22,
    result: '',
    section: 5,
    name: 'duis faucibus',
    project: 'Household',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: 'DF251D02',
    done: 'FALSE',
    repeat: '9 7 9 5 0',
    estimate: 30,
    result: '',
    section: 5,
    name: 'faucibus accumsan',
    project: 'Grooming',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '203532BB',
    done: 'FALSE',
    repeat: '',
    estimate: 14,
    result: '',
    section: 5,
    name: 'orci eget',
    project: 'Work',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '6DB13996',
    done: 'FALSE',
    repeat: '',
    estimate: 6,
    result: '',
    section: 6,
    name: 'integer aliquet',
    project: 'Create App',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: 'AA908CBD',
    done: 'FALSE',
    repeat: '4 9 2 3 5',
    estimate: 3,
    result: '',
    section: 6,
    name: 'nisl ut',
    project: 'Learn English',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: 'A9CAF361',
    done: 'FALSE',
    repeat: '8 8 3 9 0',
    estimate: 30,
    result: '',
    section: 6,
    name: 'felis eu',
    project: 'Transport',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '8A6E6238',
    done: 'FALSE',
    repeat: '1 9 7 9 5',
    estimate: 30,
    result: '',
    section: 6,
    name: 'aliquet massa',
    project: 'Household',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: 'BB8821B1',
    done: 'FALSE',
    repeat: '3 9 9 0 6',
    estimate: 22,
    result: '',
    section: 6,
    name: 'proin risus',
    project: 'Create App',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '2A36EC08',
    done: 'FALSE',
    repeat: '',
    estimate: 22,
    result: '',
    section: 7,
    name: 'eget eleifend',
    project: 'Create App',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '9D6903BB',
    done: 'FALSE',
    repeat: '',
    estimate: 23,
    result: '',
    section: 7,
    name: 'natoque penatibus',
    project: 'Create App',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '5D60996C',
    done: 'FALSE',
    repeat: '9 2 2 0 3',
    estimate: 24,
    result: '',
    section: 7,
    name: 'ligula pellentesque',
    project: 'Hobby',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '2DF7F46D',
    done: 'FALSE',
    repeat: '3 6 3 6 0',
    estimate: 10,
    result: '',
    section: 7,
    name: 'a feugiat',
    project: 'Hobby',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: 'B57A59DF',
    done: 'FALSE',
    repeat: '3 2 2 0 5',
    estimate: 5,
    result: '',
    section: 8,
    name: 'eu nibh',
    project: 'Household',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: '516DBE17',
    done: 'FALSE',
    repeat: '',
    estimate: 7,
    result: '',
    section: 8,
    name: 'quam a',
    project: 'Rest',
    start: '',
    end: '',
    date: '2020-04-30',
  },
  {
    id: 'EF49517B',
    done: 'FALSE',
    repeat: '',
    estimate: 6,
    result: '',
    section: 8,
    name: 'non lectus',
    project: 'Rest',
    start: '',
    end: '',
    date: '2020-04-30',
  },
]
